name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17.0.14'
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Build and test
        run: sbt test